{% set name = "ifes-apt-tc-data-modeling" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ifes_apt_tc_data_modeling-{{ version }}.tar.gz
  sha256: b9769544c01ed971cdad26d4810207345ecf49854215624ed763da09a760ef47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<=3.12
    - setuptools
    - pip
  run:
    - python >=3.8,<=3.12
    - h5py >=3.6.0
    - numpy >=1.21.2
    - pandas
    - ase >=3.19.0
    - radioactivedecay >=0.4.16
    - flatdict
    - xmltodict
    - pytables

test:
  imports:
    - ifes_apt_tc_data_modeling
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Foster exchange about data models and work towards clear specifications of file formats and data models in the research field of atom probe microscopy.
  license: Apache-2.0
  license_file: LICENSE.txt
  home: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling
  doc_url: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling
  dev_url: https://github.com/atomprobe-tc/ifes_apt_tc_data_modeling

extra:
  recipe-maintainers:
    - srmnitc
    - mkuehbach
